export const ERROR_MESSAGE = {
    ALL_FIELDS_REQUIRED: 'All fields are required',
    USER_NOT_FOUND: 'User not found',
    EMAIL_OR_USERNAME_EXISTS: 'Email or Username already exists',
    EMAIL_AND_PASSWORD_REQUIRED: 'Email and Password are required',
    INVALID_CREDENTIALS: 'Invalid Credentials',
    UNAUTHORIZED_TOKEN_NOT_FOUND: 'Unauthorized - Token not found',
    TOKEN_NOT_FOUND: 'Token not found',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    UNAUTHORIZED_USER: 'Unauthorized - User not found',
    TOKEN_NOT_FOUND_OR_EXPIRED: 'Unauthorized - Token not found or expired',
    TOKEN_MISMATCH: 'Unauthorized - Token mismatch',
    INVALID_TOKEN: 'Unauthorized - Invalid token',
    SOMETHING_ERROR: 'Something went wrong',
    USER_ALREADY_EXISTS: 'User already exists',
    POST_NOT_FOUND: 'Post not found',
    COMMENT_NOT_FOUND: 'Comment not found',
    RECEIVER_ID_REQUIRED: 'Receiver Id required',
    FRIEND_REQUEST_ALREADY_EXISTS: 'Friend request already exists',
    FRIEND_REQUEST_SENT_SUCCESSFULLY: 'Friend request sent successfully',
    REQUESTER_ID_REQUIRED: 'Requester Id required',
    FRIEND_REQUEST_NOT_FOUND: 'Friend request not found',
    USER_ALREADY_TAGGED: 'User already tagged',
    RECIPIENT_USER_NOT_FOUND: 'Recipient user not found',
    PRIVATE_PROFILE: 'User has a private profile',
    USER_NOT_FRIENDS: 'User not friends',
    PROFILE_UPLOAD_FAILED: 'Profile upload failed',
    INVALID_NOTIFICATION_SETTING: 'Invalid notification settings',
    INVALID_USER_IDS_FORMAT: 'Invalid user ids format',
    IMAGE_UPLOAD_FAILED: 'Image upload failed',
};

export const SUCCESS_MESSAGE = {
    USER_REGISTERED_SUCCESSFULLY: 'User Registered successfully',
    USER_LOGIN_SUCCESSFULLY: 'User Login Successfully',
    USER_LOGOUT_SUCCESSFULLY: 'User Logout Successfully',
    POST_CREATED_SUCCESSFULLY: 'Post created successfully',
    POST_FETCHED_SUCCESSFULLY: 'Post fetched successfully',
    POST_DELETED_SUCCESSFULLY: 'Post deleted successfully',
    COMMENT_CREATED_SUCCESSFULLY: 'Comment created successfully',
    COMMENT_FETCHED_SUCCESSFULLY: 'Comment fetched successfully',
    COMMENT_DELETED_SUCCESSFULLY: 'Comment deleted successfully',
    FRIEND_REQUEST_SENT_SUCCESSFULLY: 'Friend request sent successfully',
    FRIEND_REQUEST_ACCEPTED_SUCCESSFULLY: 'Friend request accepted successfully',
    FRIEND_REQUEST_REJECTED: 'Friend request rejected.',
    FRIENDS_FETCHED_SUCCESSFULLY: 'Friends fetched successfully',
    USER_TAGGED_SUCCESSFULLY: 'User tagged successfully',
    POST_LIKED_SUCCESSFULLY: 'Post liked successfully',
    COMMENT_LIKED_SUCCESSFULLY: 'Comment liked successfully',
    POST_SHARED_SUCCESSFULLY: 'Post shared successfully',
    PROFILE_UPLOAD_SUCCESSFULLY: 'Profile upload successfully',
    NOTIFICATION_SETTING_UPDATED: 'Notification settings updated successfully',
    CHAT_ROOM_CREATED_SUCCESSFULLY: 'Chat room created successfully',
    CHAT_ROOM_MESSAGE_RETRIEVED_SUCCESSFULLY: 'Chat room messages retrieved successfully',
    MESSAGE_SENT_SUCCESSFULLY: 'Message sent successfully',
};


